exports.CELL_SIZE = 40;
exports.CELL_MARGIN = 2;
exports.MAP_WIDTH = 1200;
exports.MAP_HEIGHT = 1200;
exports.NUM_WALL = 20; //
exports.VIEW_FIELD = 8;
exports.PLAYER_INITIAL_HP = 100;
exports.PLAYER_INITIAL_AD = 5;
exports.WALL_CHANCE = 0.1;
exports.ITEM_CHANCE = 0.07;
exports.INFINITY_CHANCE = 0.1;
exports.WARMOG_CHANCE = 0.1;
exports.HEALTH_POTION_CHANCE = 0.2;
exports.MONSTER_CHANCE = 0.03;
exports.WOLF_CHANCE = 1;